/*
    Copyright (C) 2016 EOSYSTEM CO., LTD. (www.eosystem.com)

    guiid.h
        this file is part of amod-mainapp

    written by
        Seung-hwan, Park (shpark2@eosystem.com)
*/

#ifndef _GUIID_H_
#define _GUIID_H_


/* macro define : guiid - menu */
#define GUIID_MENU_IRCONF                   0x1000
#define GUIID_MENU_TARGET                   0x1001
#define GUIID_MENU_DEVCONF                  0x1002
/* macro define : guiid - factory mode menu*/
#define GUIID_FTMENU_DIST_CORRECT			0x1003
#define GUIID_FTMENU_ANGLE_CORRECT			0x1004
#define GUIID_FTMENU_SENSOR_CORRECT			0x1005
#define GUIID_FTMENU_IR_ARRAY				0x1006
#define GUIID_FTMENU_FW_UPDATE				0x1007

/* macro define : guiid -submenu */
#define GUIID_SUBMENU_IREIS                 0x2000
#define GUIID_SUBMENU_IRCLR                 0x2001
#define GUIID_SUBMENU_IRGLV                 0x2002
#define GUIID_SUBMENU_IRHEQ                 0x2003
#define GUIID_SUBMENU_IRSHTR                0x2004

#define GUIID_SUBMENU_TARGET_LIST           0x2100
#define GUIID_SUBMENU_XMIT_OBLOC            0x2101
#define GUIID_SUBMENU_COMP_DMC              0x2102
#define GUIID_SUBMENU_INPUT_OBLOC           0x2103
#define GUIID_SUBMENU_INPUT_RANGE           0x2104
#define GUIID_SUBMENU_INPUT_RGATE           0x2105
#define GUIID_SUBMENU_INPUT_GRIDVAR         0x2106
#define GUIID_SUBMENU_GNSS_STATUS           0x2107

#define GUIID_SUBMENU_SET_COORDSYS          0x2200
#define GUIID_SUBMENU_TIME_CONFIG           0x2201
#define GUIID_SUBMENU_EXTERN_VOUT           0x2202
#define GUIID_SUBMENU_DMIF_TEST             0x2203
#define GUIID_SUBMENU_IBIT                  0x2204
#define GUIID_SUBMENU_SLEEP                 0x2205
#define GUIID_SUBMENU_SYSTEM_INFO           0x2206
#define GUIID_SUBMENU_XMIT_DATA             0x2207

#define GUIID_SUBMENU_SHORTDIST				0x2301
#define GUIID_SUBMENU_MIDDIST				0x2302
#define GUIID_SUBMENU_LONGDIST				0x2303
#define GUIID_SUBMENU_DISTCHECK				0x2304

#define GUIID_SUBMENU_AZM					0x2401
#define GUIID_SUBMENU_ALTT					0x2402
#define GUIID_SUBMENU_ANGLECHECK			0x2403

#define	GUIID_SUBMENU_SENSOR				0x2501
#define	GUIID_SUBMENU_SENSORCHECK			0x2502

#define GUIID_SUBMENU_IRARRAY				0x2601
#define GUIID_SUBMENU_IRSCALEINPUT			0x2602
#define GUIID_SUBMENU_IRCHECK				0x2603

#define GUIID_SUBMENU_FWUPDATE				0x2701
#define GUIID_SUBMENU_INIT					0x2702

/* macro define : guiid - dialog */
#define GUIID_DIALOG_OBMODE                 0x3000
#define GUIID_DIALOG_ADJUST                 0x3001
#define GUIID_DIALOG_IREIS                  0x3002
#define GUIID_DIALOG_IRCLR                  0x3003
#define GUIID_DIALOG_IRGLV                  0x3004
#define GUIID_DIALOG_IRHEQ                  0x3005

#define GUIID_DIALOG_TARGET_LIST            0x3006
#define GUIID_DIALOG_XMIT_OBLOC             0x3007
#define GUIID_DIALOG_COMP_DMC               0x3008
#define GUIID_DIALOG_INPUT_GRIDVAR          0x3009
#define GUIID_DIALOG_INPUT_OBLOC            0x300A
#define GUIID_DIALOG_INPUT_RANGE            0x300B
#define GUIID_DIALOG_INPUT_RGATE            0x300C
#define GUIID_DIALOG_GNSS_STATUS            0x300D

#define GUIID_DIALOG_SET_COORDSYS           0x300E
#define GUIID_DIALOG_TIME_CONFIG            0x300F
#define GUIID_DIALOG_EXTERN_VOUT            0x3010
#define GUIID_DIALOG_DMIF_TEST              0x3011
#define GUIID_DIALOG_IBIT                   0x3012
#define GUIID_DIALOG_SLEEP                  0x3013
#define GUIID_DIALOG_SYSTEM_INFO            0x3014

#define GUIID_DIALOG_INVALID_OBLOC          0x3015
#define GUIID_DIALOG_USER_OBLOC             0x3016
#define GUIID_DIALOG_AUTO_OBLOC             0x3017
#define GUIID_DIALOG_AUTO_RANGE             0x3018
#define GUIID_DIALOG_USER_RANGE             0x3019
#define GUIID_DIALOG_INVALID_RANGE          0x301A
#define GUIID_DIALOG_AUTO_GRIDVAR           0x301B
#define GUIID_DIALOG_USER_GRIDVAR           0x301C
#define GUIID_DIALOG_INVALID_GRIDVAR        0x301D
#define GUIID_DIALOG_TAQSEL                 0x301E
#define GUIID_DIALOG_ENTER_MAGCOMPMODE      0x301F
#define GUIID_DIALOG_EXIT_MAGCOMPMODE       0x3020
#define GUIID_DIALOG_RESULT_MAGCOMP         0x3021
#define GUIID_DIALOG_RETRY_MAGCOMP          0x3022
#define GUIID_DIALOG_APPLY_MAGPARM          0x3023
#define GUIID_DIALOG_MAGCOMP_OK             0x3024
#define GUIID_DIALOG_MAGCOMP_ERRFOM         0x3025
#define GUIID_DIALOG_MAGCOMP_ERRCALC        0x3026
#define GUIID_DIALOG_MAGCOMP_ERRDAQ         0x3027
#define GUIID_DIALOG_MAGCOMP_ERRINIT        0x3028
#define GUIID_DIALOG_XMIT_TALOC             0x3029
#define GUIID_DIALOG_TERMTAQ                0x302A
#define GUIID_DIALOG_SUCCESS_XMIT           0x302B
#define GUIID_DIALOG_SUCCESS_DMIF_TEST      0x302C
#define GUIID_DIALOG_SELECT_XMITINFO        0x302D
#define GUIID_DIALOG_ENTER_STANDBY_MODE     0x302E
#define GUIID_DIALOG_LOW_VOLTAGE            0x302F
#define GUIID_DIALOG_XMIT_DATA_CONF         0x3030
#define GUIID_DIALOG_EXEC_BIT               0x3031
#define GUIID_DIALOG_BIT_PASS               0x3032
#define GUIID_DIALOG_XMIT_DATA              0x3033
#define GUIID_DIALOG_TARGET_DETAIL          0x3034
#define GUIID_DIALOG_SELECT_SHUTTER         0x3035
#define GUIID_DIALOG_COVER_IRLENS           0x3036
#define GUIID_DIALOG_DELETE_TARGET          0x3037
#define GUIID_DIALOG_SELECT_XMITINFO_TLIST  0x3038
#define GUIID_DIALOG_XMIT_TALOC_TLIST       0x3039


/* factory mode dialog */
#define GUIID_DIALOG_SHORTDIST				0x3040
#define GUIID_DIALOG_MIDDIST				0x3041
#define GUIID_DIALOG_LONGDIST				0x3042
#define GUIID_DIALOG_DISTCHECK				0x3043
#define	GUIID_DIALOG_AZM					0x3044
#define	GUIID_DIALOG_ALTT					0x3045
#define GUIID_DIALOG_ANGLECHECK				0x3046
#define GUIID_DIALOG_SENSOR					0x3047
#define GUIID_DIALOG_SENSORCHECK			0x3048
#define GUIID_DIALOG_IRARRAY				0x3049
#define GUIID_DIALOG_IRCHECK				0x304A
#define GUIID_DIALOG_FWUPDATE				0x304B
#define GUIID_DIALOG_INIT					0x304C
#define GUIID_DIALOG_IRSCALEINPUT			0x304D
#define GUIID_DIALOG_IRARRAY_END			0x304E
#define GUIID_DIALOG_MOVE_IR				0x304F
/* end */


#define GUIID_DIALOG_NOFILE					0x3FE4
#define GUIID_DIALOG_SUCCESS_FWUPDATE		0x3FE5
#define GUIID_DIALOG_FAIL_FWUPDATE			0x3FE6
#define GUIID_DIALOG_NOSDCARD				0x3FE7
#define GUIID_DIALOG_ERROR_DMC_ERROR        0x3FE8
#define GUIID_DIALOG_BIT_FAIL               0x3FE9
#define GUIID_DIALOG_ERROR_GRIDVAR          0x3FEA
#define GUIID_DIALOG_ERROR_TIMEOUT          0x3FEB
#define GUIID_DIALOG_ERROR_NACK_CANPRO2     0x3FEC
#define GUIID_DIALOG_ERROR_NACK_CANPRO15    0x3FED
#define GUIID_DIALOG_ERROR_NACK_CANPRO19    0x3FEE
#define GUIID_DIALOG_ERROR_NACK_CANPRO25    0x3FEF
#define GUIID_DIALOG_ERROR_ZERO_RANGE       0x3FF0
#define GUIID_DIALOG_ERROR_TARGET_SHIFT     0x3FF1
#define GUIID_DIALOG_ERROR_TARGET_SIZE      0x3FF2
#define GUIID_DIALOG_ERROR_GEODCALC         0x3FF3
#define GUIID_DIALOG_ERROR_DMC_OFFLINE      0x3FF4
#define GUIID_DIALOG_ERROR_GNSS_OFFLINE     0x3FF5
#define GUIID_DIALOG_ERROR_TAQ              0x3FF6
#define GUIID_DIALOG_ERROR_ANGLE_LIMIT      0x3FF7
#define GUIID_DIALOG_ERROR_LRF_CTRL         0x3FF8
#define GUIID_DIALOG_ERROR_EVOUT_CTRL       0x3FF9
#define GUIID_DIALOG_ERROR_IRSHTR_CTRL      0x3FFA
#define GUIID_DIALOG_ERROR_IRCAM_POWER      0x3FFB
#define GUIID_DIALOG_ERROR_SHTR_CTRL        0x3FFC
#define GUIID_DIALOG_ERROR_DISP_CTRL        0x3FFD
#define GUIID_DIALOG_ERROR_IRCAM_CTRL       0x3FFE
#define GUIID_DIALOG_UNKNOWN_ERROR          0x3FFF


/* macro define : guiid - button */
#define GUIID_BUTTON_YES			        0x4000
#define GUIID_BUTTON_NO				        0x4001
#define GUIID_BUTTON_ON                     0x4002
#define GUIID_BUTTON_OFF                    0x4003
#define GUIID_BUTTON_CONFIRM                0x4004
#define GUIID_BUTTON_CANCEL                 0x4005
#define GUIID_BUTTON_MONO                   0x4006
#define GUIID_BUTTON_SEPIA                  0x4007
#define GUIID_BUTTON_SPECTRUM               0x4008
#define GUIID_BUTTON_ISOTHERM               0x4009
#define GUIID_BUTTON_GEODETIC               0x400A
#define GUIID_BUTTON_MGRS                   0x400B
#define GUIID_BUTTON_UTM                    0x400C
#define GUIID_BUTTON_GHEQ                   0x400D
#define GUIID_BUTTON_LHEQ                   0x400E
#define GUIID_BUTTON_APPLY                  0x400F
#define GUIID_BUTTON_TARGET_LOCATION        0x4010
#define GUIID_BUTTON_TARGET_SHIFT           0x4011
#define GUIID_BUTTON_DETAIL_INFO            0x4012
#define GUIID_BUTTON_XMIT_TARGET            0x4013
#define GUIID_BUTTON_DELETE_TARGET          0x4014
#define GUIID_BUTTON_CLOSE                  0x4015
#define GUIID_BUTTON_INTSHTR                0x4016
#define GUIID_BUTTON_EXTSHTR                0x4017
#define GUIID_BUTTON_SAVE					0x4018
#define GUIID_BUTTON_INIT					0x4019
#define GUIID_BUTTON_UPDATE					0x401A
#define GUIID_BUTTON_END					0x401B
#define GUIID_BUTTON_SAVE_END				0x401C

/* macro define : guiid - caption */
#define GUIID_CAPTION_OBMODE		        0x5000
#define GUIID_CAPTION_IREIS                 0x5001
#define GUIID_CAPTION_IRCLR                 0x5002
#define GUIID_CAPTION_COORDSYS              0x5003
#define GUIID_CAPTION_IRHEQ                 0x5004
#define GUIID_CAPTION_DELIMIT_YEAR          0x5005
#define GUIID_CAPTION_DELIMIT_MONTH         0x5006
#define GUIID_CAPTION_DELIMIT_TIME          0x5007
#define GUIID_CAPTION_UTC                   0x5008
#define GUIID_CAPTION_GRIDVAR_UNIT          0x5009
#define GUIID_CAPTION_RANGE_UNIT            0x500A
#define GUIID_CAPTION_EVOUT                 0x500B
#define GUIID_CAPTION_USER_OBLOC            0x500C
#define GUIID_CAPTION_AUTO_OBLOC            0x500D
#define GUIID_CAPTION_INVALID_OBLOC         0x500E
#define GUIID_CAPTION_USER_RANGE            0x500F
#define GUIID_CAPTION_AUTO_RANGE            0x5010
#define GUIID_CAPTION_INVALID_RANGE         0x5011
#define GUIID_CAPTION_UNKNOWN_ERROR         0x5012
#define GUIID_CAPTION_ERROR_IRCAM_CTRL      0x5013
#define GUIID_CAPTION_ERROR_DISP_CTRL       0x5014
#define GUIID_CAPTION_ERROR_IRCAM_POWER     0x5015
#define GUIID_CAPTION_ERROR_SHTR_CTRL       0x5016
#define GUIID_CAPTION_ERROR_IRSHTR_CTRL     0x5017
#define GUIID_CAPTION_ERROR_LRF_CTRL        0x5018
#define GUIID_CAPTION_ERROR_EVOUT_CTRL      0x5019
#define GUIID_CAPTION_ALTITUDE_UNIT         0x501A
#define GUIID_CAPTION_USER_GRIDVAR          0x501B
#define GUIID_CAPTION_AUTO_GRIDVAR          0x501C
#define GUIID_CAPTION_INVALID_GRIDVAR       0x501D
#define GUIID_CAPTION_ERROR_ANGLE_LIMIT     0x501E
#define GUIID_CAPTION_ENTER_MAGCOMPMODE     0x501F
#define GUIID_CAPTION_EXIT_MAGCOMPMODE      0x5020
#define GUIID_CAPTION_RESULT_MAGCOMP        0x5021
#define GUIID_CAPTION_APPLY_MAGPARM         0x5022
#define GUIID_CAPTION_RETRY_MAGCOMP         0x5023
#define GUIID_CAPTION_FAIL_INIT_MAGCOMP     0x5024
#define GUIID_CAPTION_MAGCOMP_OK            0x5025
#define GUIID_CAPTION_MAGCOMP_ERRFOM        0x5026
#define GUIID_CAPTION_MAGCOMP_ERRCALC       0x5027
#define GUIID_CAPTION_MAGCOMP_ERRDAQ        0x5028
#define GUIID_CAPTION_XMIT_OBLOC            0x5029
#define GUIID_CAPTION_XMIT_TALOC            0x502A
#define GUIID_CAPTION_DMIF_TEST             0x502B
#define GUIID_CAPTION_TERMTAQ               0x502C
#define GUIID_CAPTION_ERROR_ZERO_RANGE      0x502D
#define GUIID_CAPTION_ERROR_TARGET_SHIFT    0x502E
#define GUIID_CAPTION_ERROR_TARGET_SIZE     0x502F
#define GUIID_CAPTION_ERROR_GEODCALC        0x5030
#define GUIID_CAPTION_ERROR_DMC_OFFLINE     0x5031
#define GUIID_CAPTION_ERROR_GNSS_OFFLINE    0x5032
#define GUIID_CAPTION_ERROR_TAQ             0x5033
#define GUIID_CAPTION_SUCCESS_XMIT          0x5034
#define GUIID_CAPTION_ERROR_TIMEOUT         0x5035
#define GUIID_CAPTION_ERROR_NACK_CANPRO2    0x5036
#define GUIID_CAPTION_ERROR_NACK_CANPRO15   0x5037
#define GUIID_CAPTION_ERROR_NACK_CANPRO19   0x5038
#define GUIID_CAPTION_ERROR_NACK_CANPRO25   0x5039
#define GUIID_CAPTION_SUCCESS_DMIF_TEST     0x503A
#define GUIID_CAPTION_SELECT_XMITINFO       0x503B
#define GUIID_CAPTION_ENTER_STANDBY_MODE    0x503C
#define GUIID_CAPTION_ERROR_GRIDVAR         0x503D
#define GUIID_CAPTION_LOW_VOLTAGE           0x503E
#define GUIID_CAPTION_ERROR_PBIT            0x503F
#define GUIID_CAPTION_EXEC_BIT              0x5040
#define GUIID_CAPTION_BIT_PASS              0x5041
#define GUIID_CAPTION_BIT_FAIL              0x5042
#define GUIID_CAPTION_AUTO_XMIT_DATA        0x5043
#define GUIID_CAPTION_NO_TARGET             0x5044
#define GUIID_CAPTION_SELECT_SHUTTER        0x5045
#define GUIID_CAPTION_COVER_IRLENS          0x5046
#define GUIID_CAPTION_APP_VERSION           0x5047
#define GUIID_CAPTION_APP_VERSION_VALUE     0x5048
#define GUIID_CAPTION_APP_CRC32             0x5049
#define GUIID_CAPTION_APP_CRC32_VALUE       0x504A
#define GUIID_CAPTION_APP_BUILD_DATE        0x504B
#define GUIID_CAPTION_APP_BUILD_DATE_VALUE  0x504C
#define GUIID_CAPTION_RCC_PARAM             0x504D
#define GUIID_CAPTION_RCC_PARAM_VALUE0      0x504E
#define GUIID_CAPTION_RCC_PARAM_VALUE1      0x504F
#define GUIID_CAPTION_ANGULAR_OFFSET        0x5050
#define GUIID_CAPTION_ANGULAR_OFSSET_VALUE  0x5051
#define GUIID_CAPTION_EOSYSTEM              0x5052
#define GUIID_CAPTION_DELETE_TARGET         0x5053
#define GUIID_CAPTION_TAQTIME_TAG           0x5054
#define GUIID_CAPTION_TAQTIME_VAL           0x5055
#define GUIID_CAPTION_OBLOC_TAG             0x5056
#define GUIID_CAPTION_OBLOC_MGRS            0x5057
#define GUIID_CAPTION_OBLOC_UTM             0x5058
#define GUIID_CAPTION_OBLOC_GEODETIC        0x5059
#define GUIID_CAPTION_OBALT_TAG             0x505A
#define GUIID_CAPTION_OBALT_VAL             0x505B
#define GUIID_CAPTION_FWDAZ_TAG             0x505C
#define GUIID_CAPTION_FWDAZ_VAL             0x505D
#define GUIID_CAPTION_FWDEL_TAG             0x505E
#define GUIID_CAPTION_FWDEL_VAL             0x505F
#define GUIID_CAPTION_HDIST_TAG             0x5060
#define GUIID_CAPTION_HDIST_VAL             0x5061
#define GUIID_CAPTION_SDIST_TAG             0x5062
#define GUIID_CAPTION_SDIST_VAL             0x5063
#define GUIID_CAPTION_TGTLOC_TAG            0x5064
#define GUIID_CAPTION_TGTLOC_MGRS           0x5065
#define GUIID_CAPTION_TGTLOC_UTM            0x5066
#define GUIID_CAPTION_TGTLOC_GEODETIC       0x5067
#define GUIID_CAPTION_TGTALT_TAG            0x5068
#define GUIID_CAPTION_TGTALT_VAL            0x5069
#define GUIID_CAPTION_CIRCULAR_TARGET_TAG   0x506A
#define GUIID_CAPTION_CIRCULAR_TARGET_VAL   0x506B
#define GUIID_CAPTION_SQUARE_TARGET_TAG     0x506C
#define GUIID_CAPTION_SQUARE_TARGET_VAL     0x506D
#define GUIID_CAPTION_ADJUSTMENT_TAG        0x506E
#define GUIID_CAPTION_ADJUSTMENT_VAL        0x506F
#define GUIID_CAPTION_ATTITUDE_TAG          0x5070
#define GUIID_CAPTION_ATTITUDE_VAL          0x5071
#define GUIID_CAPTION_ADJUSTED_AZIMUTH_TAG  0x5072
#define GUIID_CAPTION_ADJUSTED_AZIMUTH_VAL  0x5073
#define GUIID_CAPTION_SHORTDIST				0x5074
#define GUIID_CAPTION_MIDDIST				0x5075
#define GUIID_CAPTION_LONGDIST				0x5076
#define GUIID_CAPTION_DISTCHECK				0x5077
#define GUIID_CAPTION_AZM					0x5078
#define GUIID_CAPTION_ALTT					0x5079
#define GUIID_CAPTION_ANGLECHECK			0x507A
#define GUIID_CAPTION_SENSOR				0x507B
#define GUIID_CAPTION_SENSORCHECK			0x507C
#define GUIID_CAPTION_IRARRAY				0x507D
#define GUIID_CAPTION_IRCHECK				0x507E
#define GUIID_CAPTION_FWUPDATE				0x507F
#define GUIID_CAPTION_INIT					0x5080
#define GUIID_CAPTION_A						0x5081
#define GUIID_CAPTION_B						0x5082
#define GUIID_CAPTION_DECIMAL_POINT_A		0x5083
#define GUIID_CAPTION_DECIMAL_POINT_B		0x5084
#define GUIID_CAPTION_DECIMAL_POINT			0x5085
#define GUIID_CAPTION_ANGLE_UNIT			0x5086
#define GUIID_CAPTION_SHORTDIST_VAL_A		0x5087
#define GUIID_CAPTION_SHORTDIST_VAL_B		0x5088
#define GUIID_CAPTION_MIDDIST_VAL_A			0x5089
#define GUIID_CAPTION_MIDDIST_VAL_B			0x508A
#define GUIID_CAPTION_LONGDIST_VAL_A		0x508B
#define GUIID_CAPTION_LONGDIST_VAL_B		0x508C
#define GUIID_CAPTION_AZIMUTH_VAL			0x508D
#define GUIID_CAPTION_ALTITUDE_VAL			0x508E
#define GUIID_CAPTION_IRSCALEINPUT			0x508F
#define GUIID_CAPTION_FWUPDATE_ERROR		0x5090
#define GUIID_CAPTION_VERTICAL				0x5091
#define GUIID_CAPTION_HORIZONTAL			0x5092
#define GUIID_CAPTION_VERTICAL_VAL			0x5093
#define GUIID_CAPTION_HORIZONTAL_VAL		0x5094
#define GUIID_CAPTION_IRSCALEINPUT_VAL		0x5095


/* macro define : guiid - slider */
#define GUIID_SLIDER_DISPBR                 0x6000
#define GUIID_SLIDER_IRBR                   0x6001
#define GUIID_SLIDER_IRCONT                 0x6002
#define GUIID_SLIDER_IREDGE                 0x6003
#define GUIID_SLIDER_IRGAIN                 0x6004
#define GUIID_SLIDER_IRLEVEL                0x6005

/* constant macro defines : guiid - spinbox */
#define GUIID_SPINBOX_YEAR                  0x7000
#define GUIID_SPINBOX_MONTH                 0x7001
#define GUIID_SPINBOX_DAY                   0x7002
#define GUIID_SPINBOX_HOUR                  0x7003
#define GUIID_SPINBOX_MINUTE                0x7004
#define GUIID_SPINBOX_UTC_OFFSET            0x7005
#define GUIID_SPINBOX_MGRS_ZONE_DIGIT4      0x7006
#define GUIID_SPINBOX_MGRS_ZONE_DIGIT3      0x7007
#define GUIID_SPINBOX_MGRS_ZONE_DIGIT2      0x7008
#define GUIID_SPINBOX_MGRS_ZONE_DIGIT1      0x7009
#define GUIID_SPINBOX_MGRS_ZONE_DIGIT0      0x700A
#define GUIID_SPINBOX_MGRS_EASTING_DIGIT4   0x700B
#define GUIID_SPINBOX_MGRS_EASTING_DIGIT3   0x700C
#define GUIID_SPINBOX_MGRS_EASTING_DIGIT2   0x700D
#define GUIID_SPINBOX_MGRS_EASTING_DIGIT1   0x700E
#define GUIID_SPINBOX_MGRS_EASTING_DIGIT0   0x700F
#define GUIID_SPINBOX_MGRS_NORTHING_DIGIT4  0x7010
#define GUIID_SPINBOX_MGRS_NORTHING_DIGIT3  0x7011
#define GUIID_SPINBOX_MGRS_NORTHING_DIGIT2  0x7012
#define GUIID_SPINBOX_MGRS_NORTHING_DIGIT1  0x7013
#define GUIID_SPINBOX_MGRS_NORTHING_DIGIT0  0x7014
#define GUIID_SPINBOX_RANGE_DIGIT0          0x7015
#define GUIID_SPINBOX_RANGE_DIGIT1          0x7016
#define GUIID_SPINBOX_RANGE_DIGIT2          0x7017
#define GUIID_SPINBOX_RANGE_DIGIT3          0x7018
#define GUIID_SPINBOX_GRIDVAR_DIGIT0        0x7019
#define GUIID_SPINBOX_GRIDVAR_DIGIT1        0x7020
#define GUIID_SPINBOX_GRIDVAR_DIGIT2        0x7021
#define GUIID_SPINBOX_GRIDVAR_DIGIT3        0x7022
#define GUIID_SPINBOX_ALTITUDE_DIGIT0       0x7023
#define GUIID_SPINBOX_ALTITUDE_DIGIT1       0x7024
#define GUIID_SPINBOX_ALTITUDE_DIGIT2       0x7025
#define GUIID_SPINBOX_ALTITUDE_DIGIT3       0x7026
#define GUIID_SPINBOX_ALTITUDE_SIGN         0x7027
#define GUIID_SPINBOX_GRIDVAR_SIGN          0x7028
#define GUIID_SPINBOX_DIST_CORRECT_DIGITA0	0x7029
#define GUIID_SPINBOX_DIST_CORRECT_DIGITA1	0x7030
#define GUIID_SPINBOX_DIST_CORRECT_DIGITA2	0x7031
#define GUIID_SPINBOX_DIST_CORRECT_DIGITA3	0x7032
#define GUIID_SPINBOX_DIST_CORRECT_DIGITA4	0x7033
#define GUIID_SPINBOX_DIST_CORRECT_DIGITA5	0x7034
#define GUIID_SPINBOX_DIST_CORRECT_DIGITA6	0x7035
#define GUIID_SPINBOX_DIST_SIGN_A			0x7036
#define GUIID_SPINBOX_DIST_CORRECT_DIGITB0	0x7037
#define GUIID_SPINBOX_DIST_CORRECT_DIGITB1	0x7038
#define GUIID_SPINBOX_DIST_CORRECT_DIGITB2	0x7039
#define GUIID_SPINBOX_DIST_CORRECT_DIGITB3	0x7040
#define GUIID_SPINBOX_DIST_CORRECT_DIGITB4	0x7041
#define GUIID_SPINBOX_DIST_CORRECT_DIGITB5	0x7042
#define GUIID_SPINBOX_DIST_CORRECT_DIGITB6	0x7043
#define GUIID_SPINBOX_DIST_SIGN_B			0x7044
#define GUIID_SPINBOX_AZIMUTH_DIGIT0		0x7045
#define GUIID_SPINBOX_AZIMUTH_DIGIT1		0x7046
#define GUIID_SPINBOX_AZIMUTH_DIGIT2		0x7047
#define GUIID_SPINBOX_AZIMUTH_DIGIT3		0x7048
#define GUIID_SPINBOX_AZIMUTH_DIGIT4		0x7049
#define GUIID_SPINBOX_AZIMUTH_SIGN			0x704A
#define GUIID_SPINBOX_ALTITUDE_DIGIT4		0x704B
#define GUIID_SPINBOX_SENSOR_DIGITA0		0x704C
#define GUIID_SPINBOX_SENSOR_DIGITA1		0x704D
#define GUIID_SPINBOX_SENSOR_DIGITA2		0x704E
#define GUIID_SPINBOX_SENSOR_DIGITB0		0x704F
#define GUIID_SPINBOX_SENSOR_DIGITB1		0x7050
#define GUIID_SPINBOX_SENSOR_DIGITB2		0x7051


/* constant macro defines : guiid - qsel    */
#define GUIID_QSEL_TAQSEL                   0x8000

/* constant macro defines : guiid - svplot    */
#define GUIID_SVPLOT_GNSS                   0x9000

/* constant macro defines : guiid - grid */
#define GUIID_GRID_TARGET_LIST              0xA000

#endif /* _GUIID_H_ */
